"use client";

import { Column, FlexibleTable } from "@/components/shared/CTable";
import { Badge } from "@/components/ui/badge";
import React from "react";

interface User {
  [key: string]: unknown;
  id: number;
  name: string;
  email: string;
  phone: string;
  address: string;
  department: string;
  position: string;
  status: string;
  birthDate: string;
  salary: string;
  experience: string;
  education: string;
  skills: string;
  manager: string;
  startDate: string;
  workType: string;
  level: string;
  location: string;
  project: string;
  performance: string;
}

const users: User[] = [
  {
    id: 1,
    name: "Nguyễn Văn A",
    email: "a@example.com",
    phone: "0123456789",
    address: "123 Đường ABC, Quận 1, TP.HCM",
    department: "IT",
    position: "Developer",
    status: "active",
    birthDate: "1990-01-15",
    salary: "15,000,000",
    experience: "5 năm",
    education: "Đại học Bách Khoa",
    skills: "React, NodeJS, Python",
    manager: "Trần Văn B",
    startDate: "2020-03-01",
    workType: "Full-time",
    level: "Senior",
    location: "TP.HCM",
    project: "E-commerce Platform",
    performance: "Excellent",
  },
  {
    id: 2,
    name: "Trần Thị B",
    email: "b@example.com",
    phone: "0987654321",
    address: "456 Đường DEF, Quận 2, TP.HCM",
    department: "Marketing",
    position: "Manager",
    status: "active",
    birthDate: "1985-05-20",
    salary: "25,000,000",
    experience: "8 năm",
    education: "Đại học Kinh Tế",
    skills: "Marketing, SEO, Content",
    manager: "Lê Văn C",
    startDate: "2018-07-15",
    workType: "Full-time",
    level: "Manager",
    location: "TP.HCM",
    project: "Brand Development",
    performance: "Good",
  },
  {
    id: 3,
    name: "Lê Văn C",
    email: "c@example.com",
    phone: "0369258147",
    address: "789 Đường GHI, Quận 3, TP.HCM",
    department: "Sales",
    position: "Executive",
    status: "inactive",
    birthDate: "1992-12-10",
    salary: "12,000,000",
    experience: "3 năm",
    education: "Đại học Ngoại Thương",
    skills: "Sales, CRM, Communication",
    manager: "Phạm Thị D",
    startDate: "2021-01-10",
    workType: "Part-time",
    level: "Junior",
    location: "Hà Nội",
    project: "Customer Acquisition",
    performance: "Average",
  },
  {
    id: 1,
    name: "Nguyễn Văn A",
    email: "a@example.com",
    phone: "0123456789",
    address: "123 Đường ABC, Quận 1, TP.HCM",
    department: "IT",
    position: "Developer",
    status: "active",
    birthDate: "1990-01-15",
    salary: "15,000,000",
    experience: "5 năm",
    education: "Đại học Bách Khoa",
    skills: "React, NodeJS, Python",
    manager: "Trần Văn B",
    startDate: "2020-03-01",
    workType: "Full-time",
    level: "Senior",
    location: "TP.HCM",
    project: "E-commerce Platform",
    performance: "Excellent",
  },
  {
    id: 2,
    name: "Trần Thị B",
    email: "b@example.com",
    phone: "0987654321",
    address: "456 Đường DEF, Quận 2, TP.HCM",
    department: "Marketing",
    position: "Manager",
    status: "active",
    birthDate: "1985-05-20",
    salary: "25,000,000",
    experience: "8 năm",
    education: "Đại học Kinh Tế",
    skills: "Marketing, SEO, Content",
    manager: "Lê Văn C",
    startDate: "2018-07-15",
    workType: "Full-time",
    level: "Manager",
    location: "TP.HCM",
    project: "Brand Development",
    performance: "Good",
  },
  {
    id: 3,
    name: "Lê Văn C",
    email: "c@example.com",
    phone: "0369258147",
    address: "789 Đường GHI, Quận 3, TP.HCM",
    department: "Sales",
    position: "Executive",
    status: "inactive",
    birthDate: "1992-12-10",
    salary: "12,000,000",
    experience: "3 năm",
    education: "Đại học Ngoại Thương",
    skills: "Sales, CRM, Communication",
    manager: "Phạm Thị D",
    startDate: "2021-01-10",
    workType: "Part-time",
    level: "Junior",
    location: "Hà Nội",
    project: "Customer Acquisition",
    performance: "Average",
  },
  {
    id: 1,
    name: "Nguyễn Văn A",
    email: "a@example.com",
    phone: "0123456789",
    address: "123 Đường ABC, Quận 1, TP.HCM",
    department: "IT",
    position: "Developer",
    status: "active",
    birthDate: "1990-01-15",
    salary: "15,000,000",
    experience: "5 năm",
    education: "Đại học Bách Khoa",
    skills: "React, NodeJS, Python",
    manager: "Trần Văn B",
    startDate: "2020-03-01",
    workType: "Full-time",
    level: "Senior",
    location: "TP.HCM",
    project: "E-commerce Platform",
    performance: "Excellent",
  },
  {
    id: 2,
    name: "Trần Thị B",
    email: "b@example.com",
    phone: "0987654321",
    address: "456 Đường DEF, Quận 2, TP.HCM",
    department: "Marketing",
    position: "Manager",
    status: "active",
    birthDate: "1985-05-20",
    salary: "25,000,000",
    experience: "8 năm",
    education: "Đại học Kinh Tế",
    skills: "Marketing, SEO, Content",
    manager: "Lê Văn C",
    startDate: "2018-07-15",
    workType: "Full-time",
    level: "Manager",
    location: "TP.HCM",
    project: "Brand Development",
    performance: "Good",
  },
  {
    id: 3,
    name: "Lê Văn C",
    email: "c@example.com",
    phone: "0369258147",
    address: "789 Đường GHI, Quận 3, TP.HCM",
    department: "Sales",
    position: "Executive",
    status: "inactive",
    birthDate: "1992-12-10",
    salary: "12,000,000",
    experience: "3 năm",
    education: "Đại học Ngoại Thương",
    skills: "Sales, CRM, Communication",
    manager: "Phạm Thị D",
    startDate: "2021-01-10",
    workType: "Part-time",
    level: "Junior",
    location: "Hà Nội",
    project: "Customer Acquisition",
    performance: "Average",
  },
  {
    id: 1,
    name: "Nguyễn Văn A",
    email: "a@example.com",
    phone: "0123456789",
    address: "123 Đường ABC, Quận 1, TP.HCM",
    department: "IT",
    position: "Developer",
    status: "active",
    birthDate: "1990-01-15",
    salary: "15,000,000",
    experience: "5 năm",
    education: "Đại học Bách Khoa",
    skills: "React, NodeJS, Python",
    manager: "Trần Văn B",
    startDate: "2020-03-01",
    workType: "Full-time",
    level: "Senior",
    location: "TP.HCM",
    project: "E-commerce Platform",
    performance: "Excellent",
  },
  {
    id: 2,
    name: "Trần Thị B",
    email: "b@example.com",
    phone: "0987654321",
    address: "456 Đường DEF, Quận 2, TP.HCM",
    department: "Marketing",
    position: "Manager",
    status: "active",
    birthDate: "1985-05-20",
    salary: "25,000,000",
    experience: "8 năm",
    education: "Đại học Kinh Tế",
    skills: "Marketing, SEO, Content",
    manager: "Lê Văn C",
    startDate: "2018-07-15",
    workType: "Full-time",
    level: "Manager",
    location: "TP.HCM",
    project: "Brand Development",
    performance: "Good",
  },
  {
    id: 3,
    name: "Lê Văn C",
    email: "c@example.com",
    phone: "0369258147",
    address: "789 Đường GHI, Quận 3, TP.HCM",
    department: "Sales",
    position: "Executive",
    status: "inactive",
    birthDate: "1992-12-10",
    salary: "12,000,000",
    experience: "3 năm",
    education: "Đại học Ngoại Thương",
    skills: "Sales, CRM, Communication",
    manager: "Phạm Thị D",
    startDate: "2021-01-10",
    workType: "Part-time",
    level: "Junior",
    location: "Hà Nội",
    project: "Customer Acquisition",
    performance: "Average",
  },
  {
    id: 1,
    name: "Nguyễn Văn A",
    email: "a@example.com",
    phone: "0123456789",
    address: "123 Đường ABC, Quận 1, TP.HCM",
    department: "IT",
    position: "Developer",
    status: "active",
    birthDate: "1990-01-15",
    salary: "15,000,000",
    experience: "5 năm",
    education: "Đại học Bách Khoa",
    skills: "React, NodeJS, Python",
    manager: "Trần Văn B",
    startDate: "2020-03-01",
    workType: "Full-time",
    level: "Senior",
    location: "TP.HCM",
    project: "E-commerce Platform",
    performance: "Excellent",
  },
  {
    id: 2,
    name: "Trần Thị B",
    email: "b@example.com",
    phone: "0987654321",
    address: "456 Đường DEF, Quận 2, TP.HCM",
    department: "Marketing",
    position: "Manager",
    status: "active",
    birthDate: "1985-05-20",
    salary: "25,000,000",
    experience: "8 năm",
    education: "Đại học Kinh Tế",
    skills: "Marketing, SEO, Content",
    manager: "Lê Văn C",
    startDate: "2018-07-15",
    workType: "Full-time",
    level: "Manager",
    location: "TP.HCM",
    project: "Brand Development",
    performance: "Good",
  },
  {
    id: 3,
    name: "Lê Văn C",
    email: "c@example.com",
    phone: "0369258147",
    address: "789 Đường GHI, Quận 3, TP.HCM",
    department: "Sales",
    position: "Executive",
    status: "inactive",
    birthDate: "1992-12-10",
    salary: "12,000,000",
    experience: "3 năm",
    education: "Đại học Ngoại Thương",
    skills: "Sales, CRM, Communication",
    manager: "Phạm Thị D",
    startDate: "2021-01-10",
    workType: "Part-time",
    level: "Junior",
    location: "Hà Nội",
    project: "Customer Acquisition",
    performance: "Average",
  },
  {
    id: 1,
    name: "Nguyễn Văn A",
    email: "a@example.com",
    phone: "0123456789",
    address: "123 Đường ABC, Quận 1, TP.HCM",
    department: "IT",
    position: "Developer",
    status: "active",
    birthDate: "1990-01-15",
    salary: "15,000,000",
    experience: "5 năm",
    education: "Đại học Bách Khoa",
    skills: "React, NodeJS, Python",
    manager: "Trần Văn B",
    startDate: "2020-03-01",
    workType: "Full-time",
    level: "Senior",
    location: "TP.HCM",
    project: "E-commerce Platform",
    performance: "Excellent",
  },
  {
    id: 2,
    name: "Trần Thị B",
    email: "b@example.com",
    phone: "0987654321",
    address: "456 Đường DEF, Quận 2, TP.HCM",
    department: "Marketing",
    position: "Manager",
    status: "active",
    birthDate: "1985-05-20",
    salary: "25,000,000",
    experience: "8 năm",
    education: "Đại học Kinh Tế",
    skills: "Marketing, SEO, Content",
    manager: "Lê Văn C",
    startDate: "2018-07-15",
    workType: "Full-time",
    level: "Manager",
    location: "TP.HCM",
    project: "Brand Development",
    performance: "Good",
  },
  {
    id: 3,
    name: "Lê Văn C",
    email: "c@example.com",
    phone: "0369258147",
    address: "789 Đường GHI, Quận 3, TP.HCM",
    department: "Sales",
    position: "Executive",
    status: "inactive",
    birthDate: "1992-12-10",
    salary: "12,000,000",
    experience: "3 năm",
    education: "Đại học Ngoại Thương",
    skills: "Sales, CRM, Communication",
    manager: "Phạm Thị D",
    startDate: "2021-01-10",
    workType: "Part-time",
    level: "Junior",
    location: "Hà Nội",
    project: "Customer Acquisition",
    performance: "Average",
  },
  {
    id: 1,
    name: "Nguyễn Văn A",
    email: "a@example.com",
    phone: "0123456789",
    address: "123 Đường ABC, Quận 1, TP.HCM",
    department: "IT",
    position: "Developer",
    status: "active",
    birthDate: "1990-01-15",
    salary: "15,000,000",
    experience: "5 năm",
    education: "Đại học Bách Khoa",
    skills: "React, NodeJS, Python",
    manager: "Trần Văn B",
    startDate: "2020-03-01",
    workType: "Full-time",
    level: "Senior",
    location: "TP.HCM",
    project: "E-commerce Platform",
    performance: "Excellent",
  },
  {
    id: 2,
    name: "Trần Thị B",
    email: "b@example.com",
    phone: "0987654321",
    address: "456 Đường DEF, Quận 2, TP.HCM",
    department: "Marketing",
    position: "Manager",
    status: "active",
    birthDate: "1985-05-20",
    salary: "25,000,000",
    experience: "8 năm",
    education: "Đại học Kinh Tế",
    skills: "Marketing, SEO, Content",
    manager: "Lê Văn C",
    startDate: "2018-07-15",
    workType: "Full-time",
    level: "Manager",
    location: "TP.HCM",
    project: "Brand Development",
    performance: "Good",
  },
  {
    id: 3,
    name: "Lê Văn C",
    email: "c@example.com",
    phone: "0369258147",
    address: "789 Đường GHI, Quận 3, TP.HCM",
    department: "Sales",
    position: "Executive",
    status: "inactive",
    birthDate: "1992-12-10",
    salary: "12,000,000",
    experience: "3 năm",
    education: "Đại học Ngoại Thương",
    skills: "Sales, CRM, Communication",
    manager: "Phạm Thị D",
    startDate: "2021-01-10",
    workType: "Part-time",
    level: "Junior",
    location: "Hà Nội",
    project: "Customer Acquisition",
    performance: "Average",
  },
  {
    id: 1,
    name: "Nguyễn Văn A",
    email: "a@example.com",
    phone: "0123456789",
    address: "123 Đường ABC, Quận 1, TP.HCM",
    department: "IT",
    position: "Developer",
    status: "active",
    birthDate: "1990-01-15",
    salary: "15,000,000",
    experience: "5 năm",
    education: "Đại học Bách Khoa",
    skills: "React, NodeJS, Python",
    manager: "Trần Văn B",
    startDate: "2020-03-01",
    workType: "Full-time",
    level: "Senior",
    location: "TP.HCM",
    project: "E-commerce Platform",
    performance: "Excellent",
  },
  {
    id: 2,
    name: "Trần Thị B",
    email: "b@example.com",
    phone: "0987654321",
    address: "456 Đường DEF, Quận 2, TP.HCM",
    department: "Marketing",
    position: "Manager",
    status: "active",
    birthDate: "1985-05-20",
    salary: "25,000,000",
    experience: "8 năm",
    education: "Đại học Kinh Tế",
    skills: "Marketing, SEO, Content",
    manager: "Lê Văn C",
    startDate: "2018-07-15",
    workType: "Full-time",
    level: "Manager",
    location: "TP.HCM",
    project: "Brand Development",
    performance: "Good",
  },
  {
    id: 3,
    name: "Lê Văn C",
    email: "c@example.com",
    phone: "0369258147",
    address: "789 Đường GHI, Quận 3, TP.HCM",
    department: "Sales",
    position: "Executive",
    status: "inactive",
    birthDate: "1992-12-10",
    salary: "12,000,000",
    experience: "3 năm",
    education: "Đại học Ngoại Thương",
    skills: "Sales, CRM, Communication",
    manager: "Phạm Thị D",
    startDate: "2021-01-10",
    workType: "Part-time",
    level: "Junior",
    location: "Hà Nội",
    project: "Customer Acquisition",
    performance: "Average",
  },
  {
    id: 1,
    name: "Nguyễn Văn A",
    email: "a@example.com",
    phone: "0123456789",
    address: "123 Đường ABC, Quận 1, TP.HCM",
    department: "IT",
    position: "Developer",
    status: "active",
    birthDate: "1990-01-15",
    salary: "15,000,000",
    experience: "5 năm",
    education: "Đại học Bách Khoa",
    skills: "React, NodeJS, Python",
    manager: "Trần Văn B",
    startDate: "2020-03-01",
    workType: "Full-time",
    level: "Senior",
    location: "TP.HCM",
    project: "E-commerce Platform",
    performance: "Excellent",
  },
  {
    id: 2,
    name: "Trần Thị B",
    email: "b@example.com",
    phone: "0987654321",
    address: "456 Đường DEF, Quận 2, TP.HCM",
    department: "Marketing",
    position: "Manager",
    status: "active",
    birthDate: "1985-05-20",
    salary: "25,000,000",
    experience: "8 năm",
    education: "Đại học Kinh Tế",
    skills: "Marketing, SEO, Content",
    manager: "Lê Văn C",
    startDate: "2018-07-15",
    workType: "Full-time",
    level: "Manager",
    location: "TP.HCM",
    project: "Brand Development",
    performance: "Good",
  },
  {
    id: 3,
    name: "Lê Văn C",
    email: "c@example.com",
    phone: "0369258147",
    address: "789 Đường GHI, Quận 3, TP.HCM",
    department: "Sales",
    position: "Executive",
    status: "inactive",
    birthDate: "1992-12-10",
    salary: "12,000,000",
    experience: "3 năm",
    education: "Đại học Ngoại Thương",
    skills: "Sales, CRM, Communication",
    manager: "Phạm Thị D",
    startDate: "2021-01-10",
    workType: "Part-time",
    level: "Junior",
    location: "Hà Nội",
    project: "Customer Acquisition",
    performance: "Average",
  },
];

const columns: Column<User>[] = [
  { key: "id", label: "#", width: "60px", sortable: true },
  { key: "name", label: "Họ và Tên", width: "150px", sortable: true },
  { key: "email", label: "Email", width: "200px", sortable: true },
  { key: "phone", label: "Số điện thoại", width: "120px" },
  { key: "address", label: "Địa chỉ", width: "250px" },
  { key: "department", label: "Phòng ban", width: "120px", sortable: true },
  { key: "position", label: "Chức vụ", width: "120px", sortable: true },
  {
    key: "status",
    label: "Trạng thái",
    width: "100px",
    sortable: true,
    render: (value) => (
      <Badge variant={value === "active" ? "default" : "secondary"}>
        {value === "active" ? "Hoạt động" : "Nghỉ việc"}
      </Badge>
    ),
  },
  { key: "birthDate", label: "Ngày sinh", width: "120px", sortable: true },
  {
    key: "salary",
    label: "Lương",
    width: "120px",
    align: "right",
    sortable: true,
  },
  { key: "experience", label: "Kinh nghiệm", width: "100px" },
  { key: "education", label: "Học vấn", width: "180px" },
  { key: "skills", label: "Kỹ năng", width: "200px" },
  { key: "manager", label: "Quản lý", width: "150px" },
  { key: "startDate", label: "Ngày vào", width: "120px", sortable: true },
  { key: "workType", label: "Loại công việc", width: "120px" },
  {
    key: "level",
    label: "Cấp bậc",
    width: "100px",
    render: (value) => (
      <Badge
        variant="outline"
        className={
          value === "Senior"
            ? "border-green-500 text-green-600"
            : value === "Manager"
            ? "border-blue-500 text-blue-600"
            : "border-gray-500 text-gray-600"
        }
      >
        {value}
      </Badge>
    ),
  },
  { key: "location", label: "Địa điểm", width: "100px" },
  { key: "project", label: "Dự án hiện tại", width: "180px" },
  {
    key: "performance",
    label: "Hiệu suất",
    width: "120px",
    render: (value) => (
      <Badge
        className={
          value === "Excellent"
            ? "bg-green-100 text-green-800"
            : value === "Good"
            ? "bg-blue-100 text-blue-800"
            : "bg-yellow-100 text-yellow-800"
        }
      >
        {value === "Excellent"
          ? "Xuất sắc"
          : value === "Good"
          ? "Tốt"
          : "Trung bình"}
      </Badge>
    ),
  },
];

const TableHailouAi = () => {
  const [pageSize, setPageSize] = React.useState(10);
  return (
    <FlexibleTable<User>
      data={users}
      columns={columns}
      rowKey="id"
      selectable
      pagination
      pageSize={pageSize}
      currentPage={1}
      onPageChange={(page) => console.log("Trang:", page)}
      onPageSizeChange={setPageSize}
      onRowClick={(row) => console.log("Click row:", row)}
      size="md"
      tableHeight={100}
    />
  );
};

export default TableHailouAi;
